import React,{useEffect,useState} from 'react';
import { Image,Pressable,Text,View } from 'react-native';
import { useRouter } from 'expo-router';
import { Camera,Check,ImagePlus,Package } from 'lucide-react-native';
import { chooseAccountImage } from '../../services/accountImage';
import { readPendingDeliveryProof } from '../../services/completionApi';
import { useDeliveryCompletion } from '../contexts/DeliveryCompletionContext';
import { Button,Gradient,Header,type } from './Kit';
import { CompletionScreen } from './CompletionKit';
import { useZippyTheme } from './theme';
export default function DeliveryProofScreen(){
  const completion=useDeliveryCompletion(),router=useRouter(),{colors}=useZippyTheme(),[photo,setPhoto]=useState<string|null>(null),[savedPhoto,setSavedPhoto]=useState<string|null>(null),[error,setError]=useState(''),[picking,setPicking]=useState(false);
  const pedido=completion.draft?.context.pedidoId,proofId=completion.draft?.request.proofId;
  useEffect(()=>{if(!pedido||!proofId)return;let alive=true;readPendingDeliveryProof(pedido).then(uri=>{if(alive)setSavedPhoto(uri);}).catch(e=>{if(alive)setError(e instanceof Error?e.message:'Foto indisponível.');});return()=>{alive=false;};},[pedido,proofId]);
  const capture=async(camera:boolean)=>{if(picking)return;setPicking(true);setError('');try{const base64=await chooseAccountImage(camera);if(base64)setPhoto(base64);}catch(e){setError(e instanceof Error?e.message:'Não foi possível capturar a foto.');}finally{setPicking(false);}};
  const upload=async()=>{if(photo&&await completion.uploadProof(photo))router.back();};
  return <CompletionScreen><Header title="Um registro bem feito." subtitle="Comprovante da entrega" onBack={()=>router.back()}/><Text style={[type.eyebrow,{color:colors.muted}]}>FOTO DE CONFERÊNCIA</Text><Text style={{fontFamily:'ManropeExtraBold',fontSize:28,lineHeight:32,color:colors.ink,letterSpacing:-1,marginVertical:12}}>O pedido.{ '\n' }O lugar. <Text style={{color:colors.accent}}>Tudo certo.</Text></Text><Text style={[type.body,{fontSize:13,color:colors.muted}]}>Mostre o volume no local combinado.{ '\n' }Evite rostos, documentos e dados do cliente.</Text>
    <View style={{height:278,borderRadius:24,overflow:'hidden',alignItems:'center',justifyContent:'center',marginVertical:15}}><Gradient colors={['#2d3d52','#121922']}/>{photo||savedPhoto?<Image source={{uri:photo?`data:image/jpeg;base64,${photo}`:savedPhoto!}} style={{width:'100%',height:'100%'}} resizeMode="contain"/>:<View style={{width:121,height:95,backgroundColor:'#c69866',borderRadius:6,borderWidth:1,borderColor:'#e3bd8a',transform:[{rotate:'-7deg'}],boxShadow:'12px 15px 0 #7e532a,23px 29px 20px #0004',alignItems:'center',justifyContent:'center'}}><View style={{position:'absolute',left:48,width:27,height:'100%',backgroundColor:'#e7cfa1aa'}}/><Text style={{position:'absolute',bottom:12,right:12,fontFamily:'ManropeExtraBold',fontSize:20,color:'#704a2e'}}>z ↗</Text></View>}<View pointerEvents="none" style={{position:'absolute',top:28,bottom:28,left:28,right:28,borderWidth:1,borderRadius:12,borderColor:'#b7d3f766'}}/><Text style={{position:'absolute',bottom:18,color:'#bfcee1',fontFamily:'Manrope',fontSize:9,letterSpacing:1}}>{photo?'FOTO CAPTURADA · CONFIRA ANTES DE ANEXAR':savedPhoto?'FOTO ANEXADA · COMPROVANTE DO PEDIDO':'ABRA A CÂMERA PARA FOTOGRAFAR'}</Text></View>
    <View style={{gap:10}}>{photo?<><Button icon={Check} loading={completion.busy} onPress={()=>void upload()}>Anexar esta foto</Button><Button secondary icon={Camera} disabled={completion.busy} onPress={()=>void capture(true)}>Refazer foto</Button></>:<><View style={{alignItems:'center',marginTop:3}}><Pressable accessibilityRole="button" accessibilityLabel="Fotografar o pedido" accessibilityState={{disabled:picking,busy:picking}} disabled={picking} onPress={()=>void capture(true)} style={({pressed})=>({width:60,height:60,borderRadius:30,borderWidth:3,borderColor:colors.muted,alignItems:'center',justifyContent:'center',opacity:pressed||picking?.6:1})}><View style={{width:44,height:44,borderRadius:22,backgroundColor:colors.soft,alignItems:'center',justifyContent:'center'}}><Camera size={23} color={colors.accent}/></View></Pressable></View><Pressable accessibilityRole="button" disabled={picking} onPress={()=>void capture(false)} style={{minHeight:44,alignItems:'center',justifyContent:'center'}}><Text style={{fontFamily:'ManropeExtraBold',fontSize:10,color:colors.accent}}>Escolher foto do aparelho</Text></Pressable>{proofId&&<Button icon={Check} onPress={()=>router.back()}>Voltar à conferência</Button>}</>}</View>{!!error&&<Text accessibilityLiveRegion="polite" style={[type.small,{color:colors.danger,marginTop:12}]}>{error}</Text>}<Text style={{fontFamily:'Manrope',fontSize:8,color:colors.muted,textAlign:'center',marginTop:12}}>{completion.draft?.context.requiresProof?'Este pedido exige comprovante.':'Opcional para este pedido.'}</Text></CompletionScreen>;
}
