import React,{useEffect,useRef,useState} from 'react';
import { Animated,Image,Text,View } from 'react-native';
import { useRouter,useLocalSearchParams } from 'expo-router';
import { useIsFocused } from '@react-navigation/native';
import { Check,FileCheck,Route,Store } from 'lucide-react-native';
import { DeliveryReceipt,findDeliveryReceipt,readDeliveryProof } from '../../services/completionApi';
import { useDeliveryCompletion } from '../contexts/DeliveryCompletionContext';
import { useOperationalSession } from '../contexts/OperationalSessionContext';
import { Button,Feedback,Gradient,Header,Pill,Screen,Surface,type } from './Kit';
import { methodNames,money,ReceiptPair,CompletionScreen } from './CompletionKit';
import { useZippyTheme } from './theme';
export default function DeliverySuccessScreen(){
  const completion=useDeliveryCompletion(),turn=useOperationalSession(),router=useRouter(),{operation}=useLocalSearchParams<{operation?:string}>(),{colors,reducedMotion}=useZippyTheme(),focused=useIsFocused(),progress=useRef(new Animated.Value(reducedMotion?1:0)).current;
  const [receipt,setReceipt]=useState<DeliveryReceipt|null>(operation?null:completion.draft?.receipt||null),[error,setError]=useState(''),[photo,setPhoto]=useState<string|null>(null);
  useEffect(()=>{if(operation){let alive=true;findDeliveryReceipt(operation).then(r=>{if(alive)setReceipt(r);}).catch(e=>{if(alive)setError(e instanceof Error?e.message:'Recibo indisponível.');});return()=>{alive=false;};}},[operation]);
  useEffect(()=>{if(!focused)return;progress.setValue(reducedMotion?1:0);const animation=Animated.timing(progress,{toValue:1,duration:reducedMotion?0:700,useNativeDriver:true});animation.start();return()=>animation.stop();},[focused,reducedMotion]);
  useEffect(()=>{if(focused&&!operation)void turn.store.refreshQueue();},[focused,operation]);
  const openPhoto=async()=>{if(!receipt)return;try{setPhoto(await readDeliveryProof(receipt.operationId));}catch(e){setError(e instanceof Error?e.message:'Comprovante indisponível.');}};
  return <CompletionScreen><Header title="Entrega concluída" subtitle="Tudo no seu lugar." onBack={()=>router.replace('/')}/>{!receipt?<Feedback title="Conferindo o recibo" message={error||'A conclusão precisa estar confirmada pelo servidor.'} loading={!error}/>:<>
    <View style={{height:174,alignItems:'center',justifyContent:'center'}}><View style={{position:'absolute',width:170,height:170,borderRadius:85,borderWidth:1,borderColor:'#809ec666',transform:[{perspective:800},{rotateX:'55deg'},{rotate:'-15deg'}],boxShadow:'0 0 40px #7fa9e166'}}/><Animated.View style={{width:83,height:83,borderRadius:29,overflow:'hidden',alignItems:'center',justifyContent:'center',boxShadow:'0 10px 0 #5f8bc4,0 20px 30px #395d8d44',opacity:progress,transform:[{scale:progress.interpolate({inputRange:[0,1],outputRange:[.65,1]})},{rotate:'-12deg'}]}}><Gradient colors={['#b9d5fa','#73a8ed']}/><View style={{zIndex:1}}><Check size={40} color="#273e5d" strokeWidth={2.5}/></View></Animated.View>{!reducedMotion&&Array.from({length:18},(_,i)=><Animated.View key={i} style={{position:'absolute',left:`${20+(i*17)%65}%`,top:20+(i*13)%60,width:5,height:9,borderRadius:1,backgroundColor:['#688ebf','#cd9b68','#a8c6ee'][i%3],opacity:progress.interpolate({inputRange:[0,.6,1],outputRange:[0,1,0]}),transform:[{translateY:progress.interpolate({inputRange:[0,1],outputRange:[-35,80]})},{rotate:`${i*31}deg`}]}}/>)}</View>
    <Text style={[type.eyebrow,{color:colors.muted,textAlign:'center'}]}>MAIS UMA ENTREGA BEM FEITA.</Text><Text style={{fontFamily:'ManropeExtraBold',fontSize:32,lineHeight:35,letterSpacing:-1.3,color:colors.ink,textAlign:'center',marginVertical:13}}>Chegou.{ '\n' }Conferiu. <Text style={{color:colors.accent}}>Concluiu.</Text></Text><Text style={[type.small,{color:colors.muted,textAlign:'center'}]}>Pedido #{receipt.pedidoId} entregue para {receipt.nomeCliente||'o cliente'}.</Text>
    <Surface style={{padding:20,borderRadius:19,marginVertical:22,boxShadow:'0 15px 20px #2431410b'}}><View style={{flexDirection:'row',justifyContent:'space-between',gap:10,marginBottom:10}}><Text style={{fontFamily:'ManropeExtraBold',fontSize:12,color:colors.ink}}>Recibo de entrega</Text><Pill icon={Check}>CONCLUÍDA</Pill></View><ReceiptPair label="Horário" value={new Date(receipt.completedAtUtc).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}/><ReceiptPair label="Código" value={receipt.codeChecked?'Validado':'Não exigido'}/><ReceiptPair label="Pagamento" value={receipt.paidBeforeDelivery?'Pago antes da entrega':receipt.payments.map(p=>`${methodNames[p.method]} · ${money(p.amount)}`).join(' + ')}/>{receipt.payments.filter(p=>p.method==='dinheiro').map((p,i)=><ReceiptPair key={i} label="Troco conferido" value={money((p.cashReceived||0)-p.amount)}/>)}<Text selectable style={{fontFamily:'Manrope',fontSize:8,letterSpacing:1,color:colors.muted,textAlign:'center',borderTopWidth:1,borderStyle:'dashed',borderColor:colors.line,marginTop:13,paddingTop:14}}>ZG · {receipt.pedidoId} · {receipt.operationId.slice(0,8).toUpperCase()}</Text></Surface>
    <View style={{gap:10}}><Button icon={turn.queue?.current?Route:Store} onPress={()=>router.replace(turn.queue?.current?'/mapa':turn.queue?.routeState==='returning'?'/retornoLoja':'/')}>{turn.queue?.current?'Próxima entrega':turn.queue?.routeState==='returning'?'Voltar à loja':'Voltar ao início'}</Button>{receipt.proofId&&<Button secondary icon={FileCheck} onPress={()=>void openPhoto()}>Ver comprovante</Button>}</View>{photo&&<Image source={{uri:photo}} style={{height:260,width:'100%',marginTop:18,borderRadius:19}} resizeMode="contain"/>}{!!error&&<Feedback title="Comprovante indisponível" message={error}/>}</>}
  </CompletionScreen>;
}
