import React, { useMemo, useState } from 'react';
import { Image, Pressable, Text, View } from 'react-native';
import { Stack, useLocalSearchParams, useRouter } from 'expo-router';
import { CheckCheck, MapPin, Package, Route, ShieldCheck } from 'lucide-react-native';
import Mapa from '../components/Mapa';
import { useRouteHistoryDetail } from '../src/hooks/useRouteHistory';
import { AccountNotice, AccountScreen, MenuRow } from '../src/ui/AccountKit';
import { Header, Pill, SectionTitle, Surface, money, type } from '../src/ui/Kit';
import { WorkPair, WorkState, historyStatus } from '../src/ui/WorkKit';
import { useZippyTheme } from '../src/ui/theme';
import type { Pedido } from '../types/pedido';
export default function HistoryRouteDetailScreen() {
  const { id = '' } = useLocalSearchParams<{ id: string }>(), router = useRouter(), { colors } = useZippyTheme(), history = useRouteHistoryDetail(id), [selectedId, setSelectedId] = useState(0);
  const detail = history.data, selected = detail?.stops.find(s => s.pedidoId === selectedId) || detail?.stops[0];
  const pedidos = useMemo<Pedido[]>(() => detail?.stops.map(s => ({ id: s.pedidoId, bairro: s.district, coordinates: s.latitude != null && s.longitude != null ? { lat: s.latitude, lng: s.longitude } : undefined })) || [], [detail]);
  const segments = useMemo(() => detail?.segments.map(s => s.map(p => ({ lat: p.lat, lng: p.lng }))) || [], [detail]);
  const date = (value?: string) => value ? new Date(value).toLocaleString('pt-BR', { day: '2-digit', month: '2-digit', hour: '2-digit', minute: '2-digit' }) : 'Ainda não registrado';
  return <AccountScreen active="earnings"><Stack.Screen options={{ headerShown: false }} /><Header title="Cada detalhe registrado." subtitle="Rota · pedidos e recebimentos" onBack={() => router.back()} /><WorkState {...history} />{detail && <>
    <View style={{ height: 240, borderRadius: 23, overflow: 'hidden', marginBottom: 16 }}><Mapa pedidos={pedidos} emEntrega={false} historical pathSegments={segments} selectedPedidoId={selected?.pedidoId} onOrderPress={setSelectedId} /><View pointerEvents="none" style={{ position: 'absolute', bottom: 12, left: 12 }}><Pill icon={Route}>{detail.pathAvailable ? 'Trajeto registrado pelo GPS' : 'Percurso GPS indisponível'}</Pill></View></View>
    <Surface hero><Text style={[type.eyebrow, { color: colors.heroMuted }]}>SEU GANHO NESTA ROTA</Text><Text style={{ fontFamily: 'ManropeExtraBold', fontSize: 34, color: colors.heroInk, marginVertical: 10 }}>{money(detail.route.earnings)}</Text><Text style={[type.small, { color: colors.heroMuted }]}>{detail.route.completedCount} de {detail.route.orderCount} pedidos entregues · {date(detail.route.startedAtUtc)}</Text></Surface>
    <AccountNotice icon={ShieldCheck}>{detail.route.unpricedCount ? `${detail.route.unpricedCount} entregas ainda sem valor registrado pela loja. O ganho exibido considera somente os valores disponíveis.` : 'Ganhos por período são conferidos no acerto. O dinheiro recebido dos clientes pertence à loja.'}</AccountNotice>
    <Surface><WorkPair label="Dinheiro da loja" value={money(detail.route.storeCash)} /><WorkPair label="Retirada" value={date(detail.route.startedAtUtc)} /><WorkPair label="Fim da rota" value={date(detail.route.endedAtUtc)} /></Surface>
    <SectionTitle>Pedidos dessa viagem</SectionTitle><Surface style={{ paddingVertical: 0 }}>{detail.stops.map((s, i) => <MenuRow key={s.stopId} icon={Package} title={`#${s.pedidoId} · ${s.district || 'Destino protegido'}`} subtitle={historyStatus[s.status] || 'Em andamento'} right={<MapPin color={s.pedidoId === selected?.pedidoId ? colors.accent : colors.muted} size={18} />} onPress={() => setSelectedId(s.pedidoId)} last={i === detail.stops.length - 1} />)}</Surface>
    {selected && <><SectionTitle>{'Pedido #' + selected.pedidoId}</SectionTitle><Surface><WorkPair label="Seu ganho" value={selected.amount == null ? 'Não registrado' : selected.mode && !['delivery', 'distance'].includes(selected.mode) ? 'Remunerado por período' : money(selected.amount)} /><WorkPair label="Coleta" value={date(selected.pickedUpAtUtc)} /><WorkPair label="Chegada" value={date(selected.arrivedAtUtc)} /><WorkPair label="Conferência na retirada" value={selected.pickup ? 'Itens e extras confirmados' : 'Sem checklist registrado'} /><WorkPair label="Conferência na entrega" value={selected.delivery ? 'Itens e extras confirmados' : 'Sem checklist registrado'} />{selected.receipt && <><WorkPair label="Código" value={selected.receipt.codeChecked ? 'Conferido no servidor' : 'Não exigido'} /><WorkPair label="Pagamento" value={selected.receipt.paidBeforeDelivery ? 'Pago antes da entrega' : selected.receipt.payments.length ? 'Recebido na entrega' : 'Sem recebimento registrado no app'} />{selected.receipt.payments.map((p, i) => <WorkPair key={i} label={p.method} value={money(p.amount) + (p.cashReceived != null ? ' · troco ' + money(p.cashReceived - p.amount) : '')} />)}</>}<Text style={[type.small, { fontSize: 9, color: colors.muted, marginTop: 14 }]}>{selected.operationId || `ZG · ${selected.pedidoId} · registro operacional`}</Text></Surface>
      {!!selected.manifest?.items?.length && <Text style={[type.small, { color: colors.muted, marginTop: 18 }]}>Conteúdo registrado na retirada</Text>}
      {selected.manifest?.items?.map(item => <Surface key={item.key} style={{ marginTop: 10, flexDirection: 'row', gap: 12, alignItems: 'center' }}>{item.imageUrl && <Image source={{ uri: item.imageUrl }} style={{ width: 58, height: 58, borderRadius: 10 }} />}<View style={{ flex: 1 }}><Text style={[type.small, { fontFamily: 'ManropeExtraBold', color: colors.ink }]}>{item.quantity}× {item.name}</Text>{item.parentName && <Text style={[type.small, { fontSize: 10, color: colors.muted }]}>{item.parentName}</Text>}</View><CheckCheck size={18} color={selected.delivery?.confirmedKeys.includes(item.key) ? colors.accent : colors.muted} /></Surface>)}
      <Pressable accessibilityRole="button" onPress={() => router.push({ pathname: '/suporte', params: { category: 'delivery', pedido: selected.pedidoId } })} style={{ paddingVertical: 20 }}><Text style={[type.small, { color: colors.accent }]}>Preciso revisar esta entrega ↗</Text></Pressable>
    </>}
  </>}</AccountScreen>;
}
