import React, { useEffect, useState } from 'react';
import { Share, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { MessageCircle, Phone, Save, Share2, ShieldCheck, TriangleAlert } from 'lucide-react-native';
import { browserNativeLinking, browserNativeTest, reportBrowserMock } from '../services/browserNativeTest';
import { getSecureItem, setSecureItem } from '../utils/secureStorage';
import { useAuth } from '../src/contexts/AuthContext';
import { useOperationalSession } from '../src/contexts/OperationalSessionContext';
import { AccountNotice, AccountScreen, MenuRow } from '../src/ui/AccountKit';
import { Button, Feedback, Field, Header, SectionTitle, type } from '../src/ui/Kit';
import { useZippyTheme } from '../src/ui/theme';

export default function SafetyScreen() {
  const router = useRouter(), auth = useAuth(), turn = useOperationalSession(), { colors } = useZippyTheme();
  const [contact, setContact] = useState(''), [phone, setPhone] = useState(''), [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false), [loaded, setLoaded] = useState(false);
  const key = `zippygo.trusted-contact.${auth.user?.id}`;
  useEffect(() => { let alive = true; setContact(''); setPhone(''); setLoaded(false); setNotice(''); setError(''); getSecureItem(key).then(raw => { if (alive && raw) { const c = JSON.parse(raw); setContact(c.name || ''); setPhone(c.phone || ''); } }).catch(() => { if (alive) setError('Não foi possível recuperar o contato salvo.'); }).finally(() => { if (alive) setLoaded(true); }); return () => { alive = false; }; }, [key]);
  const run = async (fn: () => Promise<void>) => { if (busy) return; setBusy(true); setError(''); setNotice(''); try { await fn(); } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível executar a ação.'); } finally { setBusy(false); } };
  const save = () => void run(async () => { const cleaned = phone.replace(/\D/g, ''); if (!contact.trim() || cleaned.length < 10 || cleaned.length > 13) throw new Error('Informe o nome e um telefone válido com DDD.'); await setSecureItem(key, JSON.stringify({ name: contact.trim(), phone: cleaned })); setNotice('Contato salvo neste aparelho, somente para sua conta.'); });
  const share = () => void run(async () => { if (!turn.session) throw new Error('Não há turno ativo para compartilhar.'); const message = `Estou trabalhando com ${auth.estabelecimentoAtual?.nome || 'a loja'}. Turno iniciado em ${new Date(turn.session.startedAtUtc).toLocaleString('pt-BR')}. Este aviso não contém rastreamento em tempo real.`; if (browserNativeTest) { reportBrowserMock('Compartilhamento MOCK no navegador. Nenhum aviso foi enviado ao contato.'); setNotice('MOCK no navegador: nada foi compartilhado.'); return; } await Share.share({ message }); });
  return <AccountScreen><Header title="Você vem primeiro." subtitle="Central de segurança" onBack={() => router.back()} /><View style={{ width: 78, height: 78, borderRadius: 24, backgroundColor: colors.accentSoft, alignItems: 'center', justifyContent: 'center' }}><ShieldCheck size={36} color={colors.accent} /></View><Text style={[type.body, { color: colors.ink, marginTop: 20 }]}>Pare em um local seguro antes de usar o aplicativo.</Text><SectionTitle>Contato de confiança</SectionTitle><View style={{ gap: 12 }}><Field label="Nome" value={contact} onChangeText={setContact} maxLength={100} editable={loaded && !busy} /><Field label="Telefone com DDD" value={phone} onChangeText={setPhone} keyboardType="phone-pad" maxLength={20} editable={loaded && !busy} /><Button secondary icon={Save} disabled={!loaded || busy} loading={busy} onPress={save}>Salvar contato neste aparelho</Button><Button secondary icon={Phone} disabled={!phone.trim() || busy} onPress={() => void run(async () => { const n = phone.replace(/\D/g, ''); if (n.length < 10 || n.length > 13) throw new Error('Confira o telefone antes de ligar.'); await browserNativeLinking.openURL(`tel:${n}`); })}>Ligar para o contato</Button><Button secondary icon={Share2} disabled={!turn.session || busy} onPress={share}>Compartilhar aviso do turno</Button></View><AccountNotice icon={ShieldCheck}>Você escolhe o destinatário ao compartilhar. O aviso não envia localização nem habilita acompanhamento em tempo real.</AccountNotice><MenuRow icon={MessageCircle} title="Falar com o estabelecimento" disabled={!turn.session} onPress={() => router.push({ pathname: '/conversas', params: { channel: 'store' } })} /><MenuRow icon={TriangleAlert} title="Registrar situação insegura" subtitle="Solicitação para revisão pela loja · não aciona emergência" onPress={() => router.push({ pathname: '/suporte', params: { category: 'security' } })} /><SectionTitle>Ajuda urgente · Brasil</SectionTitle><View style={{ gap: 10 }}><Button danger icon={Phone} disabled={busy} onPress={() => void run(() => browserNativeLinking.openURL('tel:190'))}>Abrir discador · Polícia 190</Button><Button secondary icon={Phone} disabled={busy} onPress={() => void run(() => browserNativeLinking.openURL('tel:192'))}>Abrir discador · SAMU 192</Button></View><AccountNotice icon={TriangleAlert} warning>O aplicativo apenas abre o discador. Você precisa efetuar a ligação. Não existe acionamento automático de emergência.</AccountNotice>{!!error && <Feedback title="Ação não confirmada" message={error} />}{!!notice && <Feedback title="Contato e compartilhamento" message={notice} />}</AccountScreen>;
}
